#!/bin/bash
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░█▀▀░█░░░█░█░█▀▀░█▀▀░▀█▀░█▀▀░█▀█░▀█▀░
#░█▀▀░█░░░█░█░█▀▀░█▀▀░░█░░█░░░█▀█░░█░░
#░▀░░░▀▀▀░▀▀▀░▀░░░▀░░░▀▀▀░▀▀▀░▀░▀░░▀░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░  github.com/flufficat/qwerty  ░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

# Manually set platform as wayland(w) or X11(x)
#plat=w
#plat=x

# Testing for platform
if [[ -z $plat ]] ; then
    if   [[ $XDG_SESSION_TYPE == "wayland" ]] ; then
        plat="w"
    elif  [[ $QT_QPA_PLATFORM == "wayland" ]] ; then
        plat="w"
    elif      [[ $GDK_BACKEND == "wayland" ]] ; then
        plat="w"
    else
        plat="x"
    fi
fi

and-copy-func () {
# Creating temporary file
if [[ ! -f /tmp/andcopy.txt ]] ; then
touch /tmp/andcopy.txt 
fi

# Pasting clipboard into file
# For wayland
if   [[ $plat == "w" ]] ; then
    # Testing for input into copy command
    if [[ ! -z $1 ]] ; then
        echo "$1" >> /tmp/andcopy.txt
    elif [[ ! -z $(wl-paste) ]] ; then
        echo "$(wl-paste)" >> /tmp/andcopy.txt
    else
	echo "No input. Please copy something or put it as an arguement e.g. and-copy <word>"
	exit 1
    fi
# For X11
elif [[ $plat == "x" ]] ; then 
    #    # Testing for input into copy command
    if [[ ! -z $1 ]] ; then
        echo "$1" >> /tmp/andcopy.txt
    elif [[ ! -z $(xclip -o) ]] ; then
        echo $(xclip -o) >> /tmp/andcopy.txt
    else
	echo "No input. Please copy something or put it as an arguement e.g. and-copy <word>"
	exit 1
    fi

else
    echo "Please set the platform you are using manually in this script"
    exit 1
fi

# Editing file with preferred editor
EDITOR=/usr/bin/nvim
$EDITOR /tmp/andcopy.txt

# Copying contents out of file
if   [[ $plat == "w" ]] ; then
    echo -n $(cat /tmp/andcopy.txt) | wl-copy && : > /tmp/andcopy.txt
elif [[ $plat == "x" ]] ; then
    echo -n $(cat /tmp/andcopy.txt) | xclip -selection c && : > /tmp/andcopy.txt
else
    echo "Please set the platform you are using manually in this script"
    exit 1
fi
}

if test "$#" -gt 0; then
    case "$1" in
        -e|--edit)
	    shift
            if   [[ $plat == "w" ]] ; then
                echo -n $(cat "$1" | wofi -H 80% -W 40% --dmenu 2> /dev/null) | wl-copy && and-copy-func
            elif [[ $plat == "x" ]] ; then 
		echo -n $(cat "$1" | rofi -theme-str 'window {width: 40%;}' -dmenu) | xclip -selection c && and-copy-func
	    else
                echo "Please set the platform you are using manually in this script"
                exit 1
	    fi
	;;
        *)
            if   [[ $plat == "w" ]] ; then
                echo -n $(cat "$1" | wofi -H 80% -W 40% --dmenu 2> /dev/null) | wl-copy
            elif [[ $plat == "x" ]] ; then 
		echo -n $(cat "$1" | rofi -theme-str 'window {width: 40%;}' -dmenu) | xclip -selection c
	    else
                echo "Please set the platform you are using manually in this script"
                exit 1
	    fi
	;;
    esac
else
    echo "Please input a file to copy from."
    exit 1
fi
